//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayZekaTemelleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public Nullable<short> stock { get; set; }
        public Nullable<decimal> buyprice { get; set; }
        public Nullable<decimal> sellprice { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> dateaddpro { get; set; }
        public Nullable<bool> productcase { get; set; }
    }
}
